import React, { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    // Get language from localStorage or default to 'en'
    return localStorage.getItem('language') || 'en'
  })

  useEffect(() => {
    // Save language to localStorage whenever it changes
    localStorage.setItem('language', language)
  }, [language])

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'te' : 'en')
  }

  const translations = {
    en: {
      // Navigation
      home: 'Home',
      profile: 'Profile',
      jobs: 'Jobs',
      applications: 'Applications',
      blog: 'Blog',
      webinars: 'Webinars',
      messages: 'Messages',
      signOut: 'Sign out',
      search: 'Search',
      notifications: 'Notifications',
      
      // Common
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      save: 'Save',
      cancel: 'Cancel',
      edit: 'Edit',
      delete: 'Delete',
      create: 'Create',
      update: 'Update',
      
      // Auth
      login: 'Login',
      register: 'Register',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      firstName: 'First Name',
      lastName: 'Last Name',
      phone: 'Phone',
      
      // School specific
      schoolName: 'School Name',
      description: 'Description',
      city: 'City',
      state: 'State',
      pincode: 'Pincode',
      
      // Teacher specific
      teacher: 'Teacher',
      school: 'School',
      admin: 'Admin',
      
      // Posts
      whatsOnYourMind: "What's on your mind?",
      photoVideo: 'Photo/video',
      post: 'Post',
      like: 'Like',
      comment: 'Comment',
      share: 'Share',
      
      // Plans
      buyPremium: 'Buy Premium',
      upgrade: 'Upgrade',
      premium: 'Premium',
      free: 'Free',
      
      // Chat
      sendMessage: 'Send message',
      typeMessage: 'Type a message...',
      online: 'Online',
      offline: 'Offline',
      
      // Notifications
      newNotification: 'New notification',
      noNotifications: 'No notifications',
      viewAll: 'View all',
      
      // Dashboard
      dashboard: 'Dashboard',
      overview: 'Overview',
      analytics: 'Analytics',
      settings: 'Settings',
      
      // Job related
      jobTitle: 'Job Title',
      jobDescription: 'Job Description',
      requirements: 'Requirements',
      salary: 'Salary',
      location: 'Location',
      apply: 'Apply',
      applied: 'Applied',
      viewDetails: 'View Details',
      
      // Profile
      about: 'About',
      experience: 'Experience',
      education: 'Education',
      skills: 'Skills',
      achievements: 'Achievements',
      editProfile: 'Edit Profile',
      viewProfile: 'View Profile',
      
      // Admin
      adminPanel: 'Admin Panel',
      manageUsers: 'Manage Users',
      managePlans: 'Manage Plans',
      systemControls: 'System Controls',
      schoolPlans: 'School Plans',
      teacherPlans: 'Teacher Plans',
      enableDisable: 'Enable/disable',
      
      // Time
      now: 'Now',
      minutesAgo: 'minutes ago',
      hoursAgo: 'hours ago',
      daysAgo: 'days ago',
      weeksAgo: 'weeks ago',
      monthsAgo: 'months ago',
      yearsAgo: 'years ago',
      
      // Home page specific
      connectSchoolsWith: 'Connect Schools with',
      amazingTeachers: 'Amazing Teachers',
      ultimatePlatform: 'The ultimate platform for schools to find qualified teachers and for teachers to discover their dream teaching positions.',
      getStartedFree: 'Get Started Free',
      watchDemo: 'Watch Demo',
      forSchools: 'For Schools',
      everythingYouNeed: 'Everything You Need to Succeed',
      powerfulTools: 'Powerful tools for schools and teachers to connect and grow together',
      frequentlyAsked: 'Frequently Asked Questions',
      forJobSeekers: 'For Job Seekers',
      readyToGetStarted: 'Ready to Get Started?',
      joinThousands: 'Join thousands of schools and teachers already using TeachersHubb',
      createYourAccount: 'Create Your Account',
      learnMore: 'Learn More',
      activeJobs: 'Active Jobs',
      registeredSchools: 'Registered Schools',
      qualifiedTeachers: 'Qualified Teachers',
      successfulPlacements: 'Successful Placements',
      forSchoolsTitle: 'For Schools',
      forSchoolsDesc: 'Find qualified teachers, manage applications, and build your dream team.',
      forTeachersTitle: 'For Teachers',
      forTeachersDesc: 'Discover amazing teaching opportunities and advance your career.',
      realTimeChat: 'Real-time Chat',
      realTimeChatDesc: 'Communicate directly with schools and teachers instantly.',
      postJobOpenings: 'Post job openings',
      reviewApplications: 'Review applications',
      scheduleInterviews: 'Schedule interviews',
      trackHiringProcess: 'Track hiring process',
      browseJobListings: 'Browse job listings',
      applyWithOneClick: 'Apply with one click',
      trackApplications: 'Track applications',
      getNotifications: 'Get notifications',
      instantMessaging: 'Instant messaging',
      fileSharing: 'File sharing',
      interviewScheduling: 'Interview scheduling',
      statusUpdates: 'Status updates',
      welcome: 'Welcome',
      dashboard: 'Dashboard',
      connectingEducators: 'Connecting educators and schools across India. Simple, fast, and reliable hiring platform that transforms the way schools find amazing teachers.',
      importantLinks: 'Important Links',
      aboutUs: 'About Us',
      contactUs: 'Contact Us',
      forTeachers: 'For Teachers',
      signupForFree: 'Signup for Free',
      loginHere: 'Login Here',
      followUsOn: 'Follow us on',
      privacyPolicy: 'Privacy Policy',
      termsConditions: 'Terms & Conditions',
      fraudAlert: 'Fraud Alert',
      allRightsReserved: 'All Rights Reserved',
      
      // Authentication
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      rememberMe: 'Remember Me',
      forgotPassword: 'Forgot Password?',
      dontHaveAccount: "Don't have an account?",
      alreadyHaveAccount: "Already have an account?",
      signUp: 'Sign Up',
      signIn: 'Sign In',
      createAccount: 'Create Account',
      backToLogin: 'Back to Login',
      resetPassword: 'Reset Password',
      enterEmail: 'Enter your email',
      sendResetLink: 'Send Reset Link',
      passwordReset: 'Password Reset',
      newPassword: 'New Password',
      confirmNewPassword: 'Confirm New Password',
      updatePassword: 'Update Password',
      
      // Registration
      firstName: 'First Name',
      lastName: 'Last Name',
      mobileNumber: 'Mobile Number',
      dateOfBirth: 'Date of Birth',
      gender: 'Gender',
      address: 'Address',
      city: 'City',
      state: 'State',
      pincode: 'Pincode',
      country: 'Country',
      schoolName: 'School Name',
      institutionType: 'Institution Type',
      designation: 'Designation',
      description: 'Description',
      selectGender: 'Select Gender',
      male: 'Male',
      female: 'Other',
      selectInstitutionType: 'Select Institution Type',
      government: 'Government',
      private: 'Private',
      aided: 'Aided',
      unaided: 'Unaided',
      
      // Teacher Dashboard
      findJobs: 'Find Jobs',
      myApplications: 'My Applications',
      blogForum: 'Blog & Forum',
      webinars: 'Webinars',
      messages: 'Messages',
      profile: 'Profile',
      dashboard: 'Dashboard',
      applications: 'Applications',
      jobs: 'Jobs',
      blog: 'Blog',
      webinars: 'Webinars',
      messages: 'Messages',
      profile: 'Profile',
      
      // School Dashboard
      postJob: 'Post Job',
      manageJobs: 'Manage Jobs',
      applicants: 'Applicants',
      interviews: 'Interviews',
      analytics: 'Analytics',
      settings: 'Settings',
      
      // Job Posting
      jobTitle: 'Job Title',
      jobDescription: 'Job Description',
      requirements: 'Requirements',
      salary: 'Salary',
      location: 'Location',
      jobType: 'Job Type',
      experience: 'Experience',
      education: 'Education',
      skills: 'Skills',
      benefits: 'Benefits',
      applicationDeadline: 'Application Deadline',
      urgent: 'Urgent',
      fullTime: 'Full Time',
      partTime: 'Part Time',
      contract: 'Contract',
      temporary: 'Temporary',
      
      // Applications
      applied: 'Applied',
      shortlisted: 'Shortlisted',
      rejected: 'Rejected',
      pending: 'Pending',
      viewResume: 'View Resume',
      scheduleInterview: 'Schedule Interview',
      hire: 'Hire',
      reject: 'Reject',
      shortlist: 'Shortlist',
      applicationStatus: 'Application Status',
      applicationDate: 'Application Date',
      coverLetter: 'Cover Letter',
      
      // Profile
      personalInfo: 'Personal Information',
      professionalInfo: 'Professional Information',
      education: 'Education',
      experience: 'Experience',
      skills: 'Skills',
      achievements: 'Achievements',
      editProfile: 'Edit Profile',
      saveChanges: 'Save Changes',
      cancel: 'Cancel',
      uploadPhoto: 'Upload Photo',
      changePhoto: 'Change Photo',
      
      // Resume
      editResume: 'Edit Resume',
      viewResume: 'View Resume',
      downloadResume: 'Download Resume',
      resumeDetails: 'Resume Details',
      personalDetails: 'Personal Details',
      professionalDetails: 'Professional Details',
      workExperience: 'Work Experience',
      educationDetails: 'Education Details',
      skillsDetails: 'Skills Details',
      
      // Notifications
      notifications: 'Notifications',
      viewAllNotifications: 'View All Notifications',
      markAsRead: 'Mark as Read',
      markAllAsRead: 'Mark All as Read',
      noNotifications: 'No notifications yet',
      newNotification: 'New Notification',
      
      // Chat/Messages
      startConversation: 'Start Conversation',
      sendMessage: 'Send Message',
      typeMessage: 'Type your message...',
      online: 'Online',
      offline: 'Offline',
      lastSeen: 'Last seen',
      typing: 'Typing...',
      noMessages: 'No messages yet',
      selectConversation: 'Select a conversation',
      
      // Blog & Forum
      createPost: 'Create Post',
      writePost: 'Write a post...',
      shareThoughts: 'Share your thoughts...',
      post: 'Post',
      like: 'Like',
      comment: 'Comment',
      share: 'Share',
      viewAllComments: 'View all comments',
      writeComment: 'Write a comment...',
      noComments: 'No comments yet',
      recentPosts: 'Recent Posts',
      popularPosts: 'Popular Posts',
      categories: 'Categories',
      
      // Webinars
      upcomingWebinars: 'Upcoming Webinars',
      recordedWebinars: 'Recorded Webinars',
      joinWebinar: 'Join Webinar',
      watchRecording: 'Watch Recording',
      webinarTitle: 'Webinar Title',
      webinarDescription: 'Webinar Description',
      webinarDate: 'Webinar Date',
      webinarTime: 'Webinar Time',
      webinarDuration: 'Duration',
      presenter: 'Presenter',
      attendees: 'Attendees',
      
      // Admin
      adminDashboard: 'Admin Dashboard',
      manageUsers: 'Manage Users',
      manageSchools: 'Manage Schools',
      manageTeachers: 'Manage Teachers',
      managePlans: 'Manage Plans',
      systemSettings: 'System Settings',
      userManagement: 'User Management',
      planManagement: 'Plan Management',
      contentManagement: 'Content Management',
      
      // Forms
      required: 'Required',
      optional: 'Optional',
      submit: 'Submit',
      reset: 'Reset',
      clear: 'Clear',
      next: 'Next',
      previous: 'Previous',
      finish: 'Finish',
      continue: 'Continue',
      
      // Status Messages
      success: 'Success',
      error: 'Error',
      warning: 'Warning',
      info: 'Information',
      loading: 'Loading...',
      saving: 'Saving...',
      processing: 'Processing...',
      pleaseWait: 'Please wait...',
      
      // Common Actions
      add: 'Add',
      edit: 'Edit',
      delete: 'Delete',
      update: 'Update',
      create: 'Create',
      view: 'View',
      search: 'Search',
      filter: 'Filter',
      sort: 'Sort',
      refresh: 'Refresh',
      close: 'Close',
      open: 'Open',
      expand: 'Expand',
      collapse: 'Collapse',
      
      // Validation Messages
      fieldRequired: 'This field is required',
      invalidEmail: 'Please enter a valid email',
      passwordTooShort: 'Password must be at least 6 characters',
      passwordsDoNotMatch: 'Passwords do not match',
      invalidPhoneNumber: 'Please enter a valid phone number',
      invalidDate: 'Please enter a valid date',
      
      // File Upload
      uploadFile: 'Upload File',
      chooseFile: 'Choose File',
      dragDropFile: 'Drag and drop file here',
      fileUploaded: 'File uploaded successfully',
      uploadFailed: 'Upload failed',
      fileTooLarge: 'File is too large',
      invalidFileType: 'Invalid file type',
      
      // Pagination
      page: 'Page',
      of: 'of',
      showing: 'Showing',
      results: 'results',
      perPage: 'per page',
      goToPage: 'Go to page',
      
      // Search
      searchResults: 'Search Results',
      noResults: 'No results found',
      searchPlaceholder: 'Search...',
      advancedSearch: 'Advanced Search',
      clearSearch: 'Clear Search',
      
      // Filters
      all: 'All',
      active: 'Active',
      inactive: 'Inactive',
      verified: 'Verified',
      unverified: 'Unverified',
      premium: 'Premium',
      free: 'Free',
      
      // Time & Date
      today: 'Today',
      yesterday: 'Yesterday',
      tomorrow: 'Tomorrow',
      thisWeek: 'This Week',
      thisMonth: 'This Month',
      thisYear: 'This Year',
      lastWeek: 'Last Week',
      lastMonth: 'Last Month',
      lastYear: 'Last Year',
      
      // Common Phrases
      welcomeBack: 'Welcome Back',
      goodMorning: 'Good Morning',
      goodAfternoon: 'Good Afternoon',
      goodEvening: 'Good Evening',
      thankYou: 'Thank You',
      youAreWelcome: 'You are welcome',
      congratulations: 'Congratulations',
      wellDone: 'Well Done',
      keepItUp: 'Keep it up',
      
      // Error Messages
      somethingWentWrong: 'Something went wrong',
      tryAgain: 'Try again',
      contactSupport: 'Contact Support',
      networkError: 'Network Error',
      serverError: 'Server Error',
      notFound: 'Not Found',
      unauthorized: 'Unauthorized',
      forbidden: 'Forbidden',
      badRequest: 'Bad Request',
      
      // Success Messages
      successMessage: 'Operation completed successfully',
      dataSaved: 'Data saved successfully',
      dataUpdated: 'Data updated successfully',
      dataDeleted: 'Data deleted successfully',
      emailSent: 'Email sent successfully',
      passwordChanged: 'Password changed successfully',
      profileUpdated: 'Profile updated successfully',
      
      // Confirmation Messages
      areYouSure: 'Are you sure?',
      confirmDelete: 'Are you sure you want to delete this item?',
      confirmAction: 'Are you sure you want to perform this action?',
      changesNotSaved: 'You have unsaved changes. Are you sure you want to leave?',
      
      // Empty States
      noData: 'No data available',
      noItems: 'No items found',
      emptyList: 'List is empty',
      nothingHere: 'Nothing here yet',
      getStarted: 'Get Started',
      
      // Loading States
      pleaseWait: 'Please wait...',
      loadingData: 'Loading data...',
      processingRequest: 'Processing request...',
      savingChanges: 'Saving changes...',
      
      // Navigation
      home: 'Home',
      back: 'Back',
      forward: 'Forward',
      up: 'Up',
      down: 'Down',
      left: 'Left',
      right: 'Right',
      
      // Social
      shareOnFacebook: 'Share on Facebook',
      shareOnTwitter: 'Share on Twitter',
      shareOnLinkedIn: 'Share on LinkedIn',
      shareViaEmail: 'Share via Email',
      copyLink: 'Copy Link',
      
      // Accessibility
      accessibility: 'Accessibility',
      skipToContent: 'Skip to Content',
      skipToNavigation: 'Skip to Navigation',
      keyboardShortcuts: 'Keyboard Shortcuts',
      screenReader: 'Screen Reader',
      
      // Settings
      preferences: 'Preferences',
      accountSettings: 'Account Settings',
      privacySettings: 'Privacy Settings',
      notificationSettings: 'Notification Settings',
      languageSettings: 'Language Settings',
      themeSettings: 'Theme Settings',
      
      // Help & Support
      help: 'Help',
      support: 'Support',
      documentation: 'Documentation',
      faq: 'FAQ',
      contactUs: 'Contact Us',
      reportIssue: 'Report Issue',
      feedback: 'Feedback',
      suggestions: 'Suggestions',
      
      // Dashboard specific
      applicationsSent: 'Applications Sent',
      interviewsScheduled: 'Interviews Scheduled',
      offersReceived: 'Offers Received',
      profileViews: 'Profile Views',
      recentApplications: 'Recent Applications',
      viewAllApplications: 'View All Applications',
      noApplicationsYet: 'No applications yet',
      startApplying: 'Start applying to jobs',
      findJobs: 'Find Jobs',
      myApplications: 'My Applications',
      quickActions: 'Quick Actions',
      searchJobs: 'Search Jobs',
      updateProfile: 'Update Profile',
      viewProfile: 'View Profile',
      editResume: 'Edit Resume',
      viewResume: 'View Resume',
      welcomeBack: 'Welcome Back',
      goodMorning: 'Good Morning',
      goodAfternoon: 'Good Afternoon',
      goodEvening: 'Good Evening',
      dashboard: 'Dashboard',
      overview: 'Overview',
      statistics: 'Statistics',
      activity: 'Activity',
      recentActivity: 'Recent Activity',
      notifications: 'Notifications',
      settings: 'Settings',
      help: 'Help',
      support: 'Support',
      logout: 'Logout',
      profile: 'Profile',
      account: 'Account',
      preferences: 'Preferences',
      security: 'Security',
      privacy: 'Privacy',
      data: 'Data',
      export: 'Export',
      import: 'Import',
      backup: 'Backup',
      restore: 'Restore',
      delete: 'Delete',
      archive: 'Archive',
      unarchive: 'Unarchive',
      markAsRead: 'Mark as Read',
      markAllAsRead: 'Mark All as Read',
      clearAll: 'Clear All',
      selectAll: 'Select All',
      deselectAll: 'Deselect All',
      bulkActions: 'Bulk Actions',
      sortBy: 'Sort By',
      filterBy: 'Filter By',
      groupBy: 'Group By',
      viewAs: 'View As',
      listView: 'List View',
      gridView: 'Grid View',
      cardView: 'Card View',
      tableView: 'Table View',
      compactView: 'Compact View',
      detailedView: 'Detailed View',
      summaryView: 'Summary View',
      fullView: 'Full View',
      partialView: 'Partial View',
      minimalView: 'Minimal View',
      expandedView: 'Expanded View',
      collapsedView: 'Collapsed View',
      hiddenView: 'Hidden View',
      visibleView: 'Visible View',
      publicView: 'Public View',
      privateView: 'Private View',
      sharedView: 'Shared View',
      personalView: 'Personal View',
      teamView: 'Team View',
      organizationView: 'Organization View',
      globalView: 'Global View',
      localView: 'Local View',
      regionalView: 'Regional View',
      nationalView: 'National View',
      internationalView: 'International View',
      
      // Additional missing keys
      browseJobListings: 'Browse job listings',
      trackApplications: 'Track applications',
      completeProfile: 'Complete your profile'
    },
    te: {
      // Navigation
      home: 'హోమ్',
      profile: 'ప్రొఫైల్',
      jobs: 'ఉద్యోగాలు',
      applications: 'అప్లికేషన్లు',
      blog: 'బ్లాగ్',
      webinars: 'వెబినార్లు',
      messages: 'సందేశాలు',
      signOut: 'సైన్ అవుట్',
      search: 'వెతకండి',
      notifications: 'నోటిఫికేషన్లు',
      
      // Common
      loading: 'లోడ్ అవుతోంది...',
      error: 'లోపం',
      success: 'విజయం',
      save: 'సేవ్',
      cancel: 'రద్దు చేయండి',
      edit: 'సవరించండి',
      delete: 'తొలగించండి',
      create: 'సృష్టించండి',
      update: 'నవీకరించండి',
      
      // Auth
      login: 'లాగిన్',
      register: 'నమోదు',
      email: 'ఇమెయిల్',
      password: 'పాస్‌వర్డ్',
      confirmPassword: 'పాస్‌వర్డ్‌ని నిర్ధారించండి',
      firstName: 'మొదటి పేరు',
      lastName: 'చివరి పేరు',
      phone: 'ఫోన్',
      
      // School specific
      schoolName: 'పాఠశాల పేరు',
      description: 'వివరణ',
      city: 'నగరం',
      state: 'రాష్ట్రం',
      pincode: 'పిన్‌కోడ్',
      
      // Teacher specific
      teacher: 'ఉపాధ్యాయుడు',
      school: 'పాఠశాల',
      admin: 'అడ్మిన్',
      
      // Posts
      whatsOnYourMind: 'మీ మనసులో ఏమి ఉంది?',
      photoVideo: 'ఫోటో/వీడియో',
      post: 'పోస్ట్',
      like: 'లైక్',
      comment: 'కామెంట్',
      share: 'షేర్',
      
      // Plans
      buyPremium: 'ప్రీమియం కొనండి',
      upgrade: 'అప్‌గ్రేడ్',
      premium: 'ప్రీమియం',
      free: 'ఉచిత',
      
      // Chat
      sendMessage: 'సందేశం పంపండి',
      typeMessage: 'సందేశం టైప్ చేయండి...',
      online: 'ఆన్‌లైన్',
      offline: 'ఆఫ్‌లైన్',
      
      // Notifications
      newNotification: 'కొత్త నోటిఫికేషన్',
      noNotifications: 'నోటిఫికేషన్లు లేవు',
      viewAll: 'అన్నీ చూడండి',
      
      // Dashboard
      dashboard: 'డాష్‌బోర్డ్',
      overview: 'అవలోకనం',
      analytics: 'విశ్లేషణ',
      settings: 'సెట్టింగ్‌లు',
      
      // Job related
      jobTitle: 'ఉద్యోగ శీర్షిక',
      jobDescription: 'ఉద్యోగ వివరణ',
      requirements: 'అవసరాలు',
      salary: 'జీతం',
      location: 'స్థానం',
      apply: 'అప్లై చేయండి',
      applied: 'అప్లై చేయబడింది',
      viewDetails: 'వివరాలను చూడండి',
      
      // Profile
      about: 'గురించి',
      experience: 'అనుభవం',
      education: 'విద్య',
      skills: 'నైపుణ్యాలు',
      achievements: 'సాధనలు',
      editProfile: 'ప్రొఫైల్‌ని సవరించండి',
      viewProfile: 'ప్రొఫైల్‌ని చూడండి',
      
      // Admin
      adminPanel: 'అడ్మిన్ ప్యానెల్',
      manageUsers: 'వినియోగదారులను నిర్వహించండి',
      managePlans: 'ప్లాన్‌లను నిర్వహించండి',
      systemControls: 'సిస్టమ్ కంట్రోల్‌లు',
      schoolPlans: 'పాఠశాల ప్లాన్‌లు',
      teacherPlans: 'ఉపాధ్యాయ ప్లాన్‌లు',
      enableDisable: 'ఎనేబుల్/డిసేబుల్',
      
      // Time
      now: 'ఇప్పుడు',
      minutesAgo: 'నిమిషాల క్రితం',
      hoursAgo: 'గంటల క్రితం',
      daysAgo: 'రోజుల క్రితం',
      weeksAgo: 'వారాల క్రితం',
      monthsAgo: 'నెలల క్రితం',
      yearsAgo: 'సంవత్సరాల క్రితం',
      
      // Home page specific
      connectSchoolsWith: 'పాఠశాలలను',
      amazingTeachers: 'అద్భుతమైన ఉపాధ్యాయులతో కనెక్ట్ చేయండి',
      ultimatePlatform: 'పాఠశాలలు అర్హత కలిగిన ఉపాధ్యాయులను కనుగొనడానికి మరియు ఉపాధ్యాయులు తమ కలల టీచింగ్ స్థానాలను కనుగొనడానికి అంతిమ ప్లాట్‌ఫారమ్.',
      getStartedFree: 'ఉచితంగా ప్రారంభించండి',
      watchDemo: 'డెమో చూడండి',
      forSchools: 'పాఠశాలల కోసం',
      everythingYouNeed: 'విజయం సాధించడానికి మీకు కావలసిన ప్రతిదీ',
      powerfulTools: 'పాఠశాలలు మరియు ఉపాధ్యాయులు కనెక్ట్ అవడానికి మరియు కలిసి అభివృద్ధి చెందడానికి శక్తివంతమైన సాధనాలు',
      frequentlyAsked: 'తరచుగా అడిగే ప్రశ్నలు',
      forJobSeekers: 'ఉద్యోగ అభ్యర్థుల కోసం',
      readyToGetStarted: 'ప్రారంభించడానికి సిద్ధమా?',
      joinThousands: 'ఇప్పటికే TeachersHubbని ఉపయోగిస్తున్న వేలాది పాఠశాలలు మరియు ఉపాధ్యాయులతో చేరండి',
      createYourAccount: 'మీ ఖాతాను సృష్టించండి',
      learnMore: 'మరింత తెలుసుకోండి',
      activeJobs: 'క్రియాశీల ఉద్యోగాలు',
      registeredSchools: 'నమోదైన పాఠశాలలు',
      qualifiedTeachers: 'అర్హత కలిగిన ఉపాధ్యాయులు',
      successfulPlacements: 'విజయవంతమైన ప్లేస్‌మెంట్‌లు',
      forSchoolsTitle: 'పాఠశాలల కోసం',
      forSchoolsDesc: 'అర్హత కలిగిన ఉపాధ్యాయులను కనుగొనండి, అప్లికేషన్‌లను నిర్వహించండి మరియు మీ కలల టీమ్‌ను నిర్మించండి.',
      forTeachersTitle: 'ఉపాధ్యాయుల కోసం',
      forTeachersDesc: 'అద్భుతమైన టీచింగ్ అవకాశాలను కనుగొనండి మరియు మీ కెరీర్‌ను అభివృద్ధి చేయండి.',
      realTimeChat: 'రియల్‌టైమ్ చాట్',
      realTimeChatDesc: 'పాఠశాలలు మరియు ఉపాధ్యాయులతో నేరుగా తక్షణం కమ్యూనికేట్ చేయండి.',
      postJobOpenings: 'ఉద్యోగ ఖాళీలను పోస్ట్ చేయండి',
      reviewApplications: 'అప్లికేషన్‌లను సమీక్షించండి',
      scheduleInterviews: 'ఇంటర్‌వ్యూలను షెడ్యూల్ చేయండి',
      trackHiringProcess: 'నియామక ప్రక్రియను ట్రాక్ చేయండి',
      browseJobListings: 'ఉద్యోగ లిస్టింగ్‌లను బ్రౌజ్ చేయండి',
      applyWithOneClick: 'ఒక క్లిక్‌తో అప్లై చేయండి',
      trackApplications: 'అప్లికేషన్‌లను ట్రాక్ చేయండి',
      getNotifications: 'నోటిఫికేషన్‌లను పొందండి',
      instantMessaging: 'తక్షణ సందేశాలు',
      fileSharing: 'ఫైల్ షేరింగ్',
      interviewScheduling: 'ఇంటర్‌వ్యూ షెడ్యూలింగ్',
      statusUpdates: 'స్టేటస్ అప్‌డేట్‌లు',
      welcome: 'స్వాగతం',
      dashboard: 'డాష్‌బోర్డ్',
      connectingEducators: 'భారతదేశంలోని విద్యావేత్తలు మరియు పాఠశాలలను కనెక్ట్ చేస్తోంది. పాఠశాలలు అద్భుతమైన ఉపాధ్యాయులను కనుగొనే విధానాన్ని మార్చే సరళమైన, వేగవంతమైన మరియు నమ్మకమైన నియామక ప్లాట్‌ఫారమ్.',
      importantLinks: 'ముఖ్యమైన లింక్‌లు',
      aboutUs: 'మా గురించి',
      contactUs: 'మమ్మల్ని సంప్రదించండి',
      forTeachers: 'ఉపాధ్యాయుల కోసం',
      signupForFree: 'ఉచితంగా సైన్ అప్ చేయండి',
      loginHere: 'ఇక్కడ లాగిన్ చేయండి',
      followUsOn: 'మమ్మల్ని ఫాలో చేయండి',
      privacyPolicy: 'గోప్యతా విధానం',
      termsConditions: 'నిబంధనలు మరియు షరతులు',
      fraudAlert: 'మోసం హెచ్చరిక',
      allRightsReserved: 'అన్ని హక్కులు ప్రతిష్టాపితం',
      
      // Authentication
      email: 'ఇమెయిల్',
      password: 'పాస్‌వర్డ్',
      confirmPassword: 'పాస్‌వర్డ్‌ను నిర్ధారించండి',
      rememberMe: 'నన్ను గుర్తుంచుకో',
      forgotPassword: 'పాస్‌వర్డ్ మర్చిపోయారా?',
      dontHaveAccount: "ఖాతా లేదా?",
      alreadyHaveAccount: "ఇప్పటికే ఖాతా ఉందా?",
      signUp: 'సైన్ అప్',
      signIn: 'సైన్ ఇన్',
      createAccount: 'ఖాతా సృష్టించండి',
      backToLogin: 'లాగిన్‌కు తిరిగి వెళ్లండి',
      resetPassword: 'పాస్‌వర్డ్‌ను రీసెట్ చేయండి',
      enterEmail: 'మీ ఇమెయిల్‌ను నమోదు చేయండి',
      sendResetLink: 'రీసెట్ లింక్‌ను పంపండి',
      passwordReset: 'పాస్‌వర్డ్ రీసెట్',
      newPassword: 'కొత్త పాస్‌వర్డ్',
      confirmNewPassword: 'కొత్త పాస్‌వర్డ్‌ను నిర్ధారించండి',
      updatePassword: 'పాస్‌వర్డ్‌ను అప్‌డేట్ చేయండి',
      
      // Registration
      firstName: 'మొదటి పేరు',
      lastName: 'చివరి పేరు',
      mobileNumber: 'మొబైల్ నంబర్',
      dateOfBirth: 'జన్మతేది',
      gender: 'లింగం',
      address: 'చిరునామా',
      city: 'నగరం',
      state: 'రాష్ట్రం',
      pincode: 'పిన్‌కోడ్',
      country: 'దేశం',
      schoolName: 'పాఠశాల పేరు',
      institutionType: 'సంస్థ రకం',
      designation: 'హోదా',
      description: 'వివరణ',
      selectGender: 'లింగాన్ని ఎంచుకోండి',
      male: 'పురుషుడు',
      female: 'ఇతర',
      selectInstitutionType: 'సంస్థ రకాన్ని ఎంచుకోండి',
      government: 'ప్రభుత్వ',
      private: 'ప్రైవేట్',
      aided: 'సహాయక',
      unaided: 'సహాయరహిత',
      
      // Teacher Dashboard
      findJobs: 'ఉద్యోగాలను కనుగొనండి',
      myApplications: 'నా దరఖాస్తులు',
      blogForum: 'బ్లాగ్ & ఫోరమ్',
      webinars: 'వెబ్‌నార్లు',
      messages: 'సందేశాలు',
      profile: 'ప్రొఫైల్',
      dashboard: 'డాష్‌బోర్డ్',
      applications: 'దరఖాస్తులు',
      jobs: 'ఉద్యోగాలు',
      blog: 'బ్లాగ్',
      webinars: 'వెబ్‌నార్లు',
      messages: 'సందేశాలు',
      profile: 'ప్రొఫైల్',
      
      // School Dashboard
      postJob: 'ఉద్యోగాన్ని పోస్ట్ చేయండి',
      manageJobs: 'ఉద్యోగాలను నిర్వహించండి',
      applicants: 'దరఖాస్తుదారులు',
      interviews: 'ఇంటర్‌వ్యూలు',
      analytics: 'విశ్లేషణ',
      settings: 'సెట్టింగ్‌లు',
      
      // Job Posting
      jobTitle: 'ఉద్యోగ శీర్షిక',
      jobDescription: 'ఉద్యోగ వివరణ',
      requirements: 'అవసరాలు',
      salary: 'జీతం',
      location: 'స్థానం',
      jobType: 'ఉద్యోగ రకం',
      experience: 'అనుభవం',
      education: 'విద్య',
      skills: 'నైపుణ్యాలు',
      benefits: 'ప్రయోజనాలు',
      applicationDeadline: 'దరఖాస్తు గడువు',
      urgent: 'అత్యవసర',
      fullTime: 'పూర్తి సమయం',
      partTime: 'అర్ధ సమయం',
      contract: 'కాంట్రాక్ట్',
      temporary: 'తాత్కాలిక',
      
      // Applications
      applied: 'దరఖాస్తు చేయబడింది',
      shortlisted: 'షార్ట్‌లిస్ట్ చేయబడింది',
      rejected: 'తిరస్కరించబడింది',
      pending: 'పెండింగ్‌లో',
      viewResume: 'రెజ్యూమెను వీక్షించండి',
      scheduleInterview: 'ఇంటర్‌వ్యూను షెడ్యూల్ చేయండి',
      hire: 'నియమించుకోండి',
      reject: 'తిరస్కరించండి',
      shortlist: 'షార్ట్‌లిస్ట్ చేయండి',
      applicationStatus: 'దరఖాస్తు స్థితి',
      applicationDate: 'దరఖాస్తు తేదీ',
      coverLetter: 'కవర్ లెటర్',
      
      // Profile
      personalInfo: 'వ్యక్తిగత సమాచారం',
      professionalInfo: 'వృత్తిపరమైన సమాచారం',
      education: 'విద్య',
      experience: 'అనుభవం',
      skills: 'నైపుణ్యాలు',
      achievements: 'సాధనలు',
      editProfile: 'ప్రొఫైల్‌ను సవరించండి',
      saveChanges: 'మార్పులను సేవ్ చేయండి',
      cancel: 'రద్దు చేయండి',
      uploadPhoto: 'ఫోటోను అప్‌లోడ్ చేయండి',
      changePhoto: 'ఫోటోను మార్చండి',
      
      // Resume
      editResume: 'రెజ్యూమెను సవరించండి',
      viewResume: 'రెజ్యూమెను వీక్షించండి',
      downloadResume: 'రెజ్యూమెను డౌన్‌లోడ్ చేయండి',
      resumeDetails: 'రెజ్యూమె వివరాలు',
      personalDetails: 'వ్యక్తిగత వివరాలు',
      professionalDetails: 'వృత్తిపరమైన వివరాలు',
      workExperience: 'పని అనుభవం',
      educationDetails: 'విద్య వివరాలు',
      skillsDetails: 'నైపుణ్య వివరాలు',
      
      // Notifications
      notifications: 'నోటిఫికేషన్‌లు',
      viewAllNotifications: 'అన్ని నోటిఫికేషన్‌లను వీక్షించండి',
      markAsRead: 'చదివినట్లు గుర్తించండి',
      markAllAsRead: 'అన్నింటిని చదివినట్లు గుర్తించండి',
      noNotifications: 'ఇంకా నోటిఫికేషన్‌లు లేవు',
      newNotification: 'కొత్త నోటిఫికేషన్',
      
      // Chat/Messages
      startConversation: 'సంభాషణను ప్రారంభించండి',
      sendMessage: 'సందేశాన్ని పంపండి',
      typeMessage: 'మీ సందేశాన్ని టైప్ చేయండి...',
      online: 'ఆన్‌లైన్',
      offline: 'ఆఫ్‌లైన్',
      lastSeen: 'చివరిగా చూసినది',
      typing: 'టైప్ చేస్తోంది...',
      noMessages: 'ఇంకా సందేశాలు లేవు',
      selectConversation: 'సంభాషణను ఎంచుకోండి',
      
      // Blog & Forum
      createPost: 'పోస్ట్‌ను సృష్టించండి',
      writePost: 'పోస్ట్‌ను వ్రాయండి...',
      shareThoughts: 'మీ ఆలోచనలను షేర్ చేయండి...',
      post: 'పోస్ట్',
      like: 'ఇష్టం',
      comment: 'వ్యాఖ్య',
      share: 'షేర్ చేయండి',
      viewAllComments: 'అన్ని వ్యాఖ్యలను చూడండి',
      writeComment: 'వ్యాఖ్యను వ్రాయండి...',
      noComments: 'ఇంకా వ్యాఖ్యలు లేవు',
      recentPosts: 'ఇటీవలి పోస్ట్‌లు',
      popularPosts: 'జనాదరణ పొందిన పోస్ట్‌లు',
      categories: 'వర్గాలు',
      
      // Webinars
      upcomingWebinars: 'రాబోయే వెబ్‌నార్లు',
      recordedWebinars: 'రికార్డ్ చేయబడిన వెబ్‌నార్లు',
      joinWebinar: 'వెబ్‌నార్‌లో చేరండి',
      watchRecording: 'రికార్డింగ్‌ను చూడండి',
      webinarTitle: 'వెబ్‌నార్ శీర్షిక',
      webinarDescription: 'వెబ్‌నార్ వివరణ',
      webinarDate: 'వెబ్‌నార్ తేదీ',
      webinarTime: 'వెబ్‌నార్ సమయం',
      webinarDuration: 'వ్యవధి',
      presenter: 'ప్రజెంటర్',
      attendees: 'హాజరైనవారు',
      
      // Admin
      adminDashboard: 'అడ్మిన్ డాష్‌బోర్డ్',
      manageUsers: 'వినియోగదారులను నిర్వహించండి',
      manageSchools: 'పాఠశాలలను నిర్వహించండి',
      manageTeachers: 'ఉపాధ్యాయులను నిర్వహించండి',
      managePlans: 'ప్లాన్‌లను నిర్వహించండి',
      systemSettings: 'సిస్టమ్ సెట్టింగ్‌లు',
      userManagement: 'వినియోగదారు నిర్వహణ',
      planManagement: 'ప్లాన్ నిర్వహణ',
      contentManagement: 'కంటెంట్ నిర్వహణ',
      
      // Forms
      required: 'అవసరం',
      optional: 'ఐచ్ఛికం',
      submit: 'సమర్పించండి',
      reset: 'రీసెట్ చేయండి',
      clear: 'క్లియర్ చేయండి',
      next: 'తదుపరి',
      previous: 'మునుపటి',
      finish: 'ముగించండి',
      continue: 'కొనసాగించండి',
      
      // Status Messages
      success: 'విజయం',
      error: 'లోపం',
      warning: 'హెచ్చరిక',
      info: 'సమాచారం',
      loading: 'లోడ్ అవుతోంది...',
      saving: 'సేవ్ చేస్తోంది...',
      processing: 'ప్రాసెస్ చేస్తోంది...',
      pleaseWait: 'దయచేసి వేచి ఉండండి...',
      
      // Common Actions
      add: 'జోడించండి',
      edit: 'సవరించండి',
      delete: 'తొలగించండి',
      update: 'అప్‌డేట్ చేయండి',
      create: 'సృష్టించండి',
      view: 'వీక్షించండి',
      search: 'శోధించండి',
      filter: 'ఫిల్టర్ చేయండి',
      sort: 'క్రమబద్ధీకరించండి',
      refresh: 'రిఫ్రెష్ చేయండి',
      close: 'మూసివేయండి',
      open: 'తెరవండి',
      expand: 'విస్తరించండి',
      collapse: 'కుదించండి',
      
      // Validation Messages
      fieldRequired: 'ఈ ఫీల్డ్ అవసరం',
      invalidEmail: 'దయచేసి సరైన ఇమెయిల్‌ను నమోదు చేయండి',
      passwordTooShort: 'పాస్‌వర్డ్ కనీసం 6 అక్షరాలుగా ఉండాలి',
      passwordsDoNotMatch: 'పాస్‌వర్డ్‌లు సరిపోలవు',
      invalidPhoneNumber: 'దయచేసి సరైన ఫోన్ నంబర్‌ను నమోదు చేయండి',
      invalidDate: 'దయచేసి సరైన తేదీని నమోదు చేయండి',
      
      // File Upload
      uploadFile: 'ఫైల్‌ను అప్‌లోడ్ చేయండి',
      chooseFile: 'ఫైల్‌ను ఎంచుకోండి',
      dragDropFile: 'ఫైల్‌ను ఇక్కడ లాగి వదలండి',
      fileUploaded: 'ఫైల్ విజయవంతంగా అప్‌లోడ్ చేయబడింది',
      uploadFailed: 'అప్‌లోడ్ విఫలమైంది',
      fileTooLarge: 'ఫైల్ చాలా పెద్దది',
      invalidFileType: 'చెల్లని ఫైల్ రకం',
      
      // Pagination
      page: 'పేజీ',
      of: 'లో',
      showing: 'చూపిస్తోంది',
      results: 'ఫలితాలు',
      perPage: 'పేజీకి',
      goToPage: 'పేజీకి వెళ్లండి',
      
      // Search
      searchResults: 'శోధన ఫలితాలు',
      noResults: 'ఫలితాలు కనుగొనబడలేదు',
      searchPlaceholder: 'శోధించండి...',
      advancedSearch: 'అధునాతన శోధన',
      clearSearch: 'శోధనను క్లియర్ చేయండి',
      
      // Filters
      all: 'అన్ని',
      active: 'క్రియాశీల',
      inactive: 'నిష్క్రియ',
      verified: 'ధృవీకరించబడింది',
      unverified: 'ధృవీకరించబడలేదు',
      premium: 'ప్రీమియం',
      free: 'ఉచితం',
      
      // Time & Date
      today: 'ఈరోజు',
      yesterday: 'నిన్న',
      tomorrow: 'రేపు',
      thisWeek: 'ఈ వారం',
      thisMonth: 'ఈ నెల',
      thisYear: 'ఈ సంవత్సరం',
      lastWeek: 'గత వారం',
      lastMonth: 'గత నెల',
      lastYear: 'గత సంవత్సరం',
      
      // Common Phrases
      welcomeBack: 'మళ్లీ స్వాగతం',
      goodMorning: 'శుభోదయం',
      goodAfternoon: 'శుభ మధ్యాహ్నం',
      goodEvening: 'శుభ సాయంత్రం',
      thankYou: 'ధన్యవాదాలు',
      youAreWelcome: 'మీరు స్వాగతం',
      congratulations: 'అభినందనలు',
      wellDone: 'బాగా చేసారు',
      keepItUp: 'ఇలాగే కొనసాగించండి',
      
      // Error Messages
      somethingWentWrong: 'ఏదో తప్పు జరిగింది',
      tryAgain: 'మళ్లీ ప్రయత్నించండి',
      contactSupport: 'మద్దతును సంప్రదించండి',
      networkError: 'నెట్‌వర్క్ లోపం',
      serverError: 'సర్వర్ లోపం',
      notFound: 'కనుగొనబడలేదు',
      unauthorized: 'అనధికార',
      forbidden: 'నిషేధించబడింది',
      badRequest: 'చెడు అభ్యర్థన',
      
      // Success Messages
      successMessage: 'ఆపరేషన్ విజయవంతంగా పూర్తయింది',
      dataSaved: 'డేటా విజయవంతంగా సేవ్ చేయబడింది',
      dataUpdated: 'డేటా విజయవంతంగా అప్‌డేట్ చేయబడింది',
      dataDeleted: 'డేటా విజయవంతంగా తొలగించబడింది',
      emailSent: 'ఇమెయిల్ విజయవంతంగా పంపబడింది',
      passwordChanged: 'పాస్‌వర్డ్ విజయవంతంగా మార్చబడింది',
      profileUpdated: 'ప్రొఫైల్ విజయవంతంగా అప్‌డేట్ చేయబడింది',
      
      // Confirmation Messages
      areYouSure: 'మీరు ఖచ్చితంగా?',
      confirmDelete: 'మీరు ఖచ్చితంగా ఈ అంశాన్ని తొలగించాలనుకుంటున్నారా?',
      confirmAction: 'మీరు ఖచ్చితంగా ఈ చర్యను చేయాలనుకుంటున్నారా?',
      changesNotSaved: 'మీకు సేవ్ చేయని మార్పులు ఉన్నాయి. మీరు ఖచ్చితంగా వెళ్లాలనుకుంటున్నారా?',
      
      // Empty States
      noData: 'డేటా అందుబాటులో లేదు',
      noItems: 'అంశాలు కనుగొనబడలేదు',
      emptyList: 'జాబితా ఖాళీగా ఉంది',
      nothingHere: 'ఇక్కడ ఇంకా ఏమీ లేదు',
      getStarted: 'ప్రారంభించండి',
      
      // Loading States
      pleaseWait: 'దయచేసి వేచి ఉండండి...',
      loadingData: 'డేటా లోడ్ అవుతోంది...',
      processingRequest: 'అభ్యర్థనను ప్రాసెస్ చేస్తోంది...',
      savingChanges: 'మార్పులను సేవ్ చేస్తోంది...',
      
      // Navigation
      home: 'హోమ్',
      back: 'వెనుకకు',
      forward: 'ముందుకు',
      up: 'పైకి',
      down: 'క్రిందికి',
      left: 'ఎడమ',
      right: 'కుడి',
      
      // Social
      shareOnFacebook: 'ఫేస్‌బుక్‌లో షేర్ చేయండి',
      shareOnTwitter: 'ట్విటర్‌లో షేర్ చేయండి',
      shareOnLinkedIn: 'లింక్డ్‌ఇన్‌లో షేర్ చేయండి',
      shareViaEmail: 'ఇమెయిల్ ద్వారా షేర్ చేయండి',
      copyLink: 'లింక్‌ను కాపీ చేయండి',
      
      // Accessibility
      accessibility: 'అనుకూలత',
      skipToContent: 'కంటెంట్‌కు వెళ్లండి',
      skipToNavigation: 'నావిగేషన్‌కు వెళ్లండి',
      keyboardShortcuts: 'కీబోర్డ్ షార్ట్‌కట్‌లు',
      screenReader: 'స్క్రీన్ రీడర్',
      
      // Settings
      preferences: 'ప్రాధాన్యతలు',
      accountSettings: 'ఖాతా సెట్టింగ్‌లు',
      privacySettings: 'గోప్యతా సెట్టింగ్‌లు',
      notificationSettings: 'నోటిఫికేషన్ సెట్టింగ్‌లు',
      languageSettings: 'భాషా సెట్టింగ్‌లు',
      themeSettings: 'థీమ్ సెట్టింగ్‌లు',
      
      // Help & Support
      help: 'సహాయం',
      support: 'మద్దతు',
      documentation: 'డాక్యుమెంటేషన్',
      faq: 'తరచుగా అడిగే ప్రశ్నలు',
      contactUs: 'మమ్మల్ని సంప్రదించండి',
      reportIssue: 'సమస్యను నివేదించండి',
      feedback: 'ఫీడ్‌బ్యాక్',
      suggestions: 'సూచనలు',
      
      // Dashboard specific
      applicationsSent: 'దరఖాస్తులు పంపబడ్డాయి',
      interviewsScheduled: 'ఇంటర్‌వ్యూలు షెడ్యూల్ చేయబడ్డాయి',
      offersReceived: 'ఆఫర్‌లు అందుకున్నారు',
      profileViews: 'ప్రొఫైల్ వీక్షణలు',
      recentApplications: 'ఇటీవలి దరఖాస్తులు',
      viewAllApplications: 'అన్ని దరఖాస్తులను వీక్షించండి',
      noApplicationsYet: 'ఇంకా దరఖాస్తులు లేవు',
      startApplying: 'ఉద్యోగాలకు దరఖాస్తు చేయడం ప్రారంభించండి',
      findJobs: 'ఉద్యోగాలను కనుగొనండి',
      myApplications: 'నా దరఖాస్తులు',
      quickActions: 'త్వరిత చర్యలు',
      searchJobs: 'ఉద్యోగాలను శోధించండి',
      updateProfile: 'ప్రొఫైల్‌ను అప్‌డేట్ చేయండి',
      viewProfile: 'ప్రొఫైల్‌ను వీక్షించండి',
      editResume: 'రెజ్యూమెను సవరించండి',
      viewResume: 'రెజ్యూమెను వీక్షించండి',
      welcomeBack: 'మళ్లీ స్వాగతం',
      goodMorning: 'శుభోదయం',
      goodAfternoon: 'శుభ మధ్యాహ్నం',
      goodEvening: 'శుభ సాయంత్రం',
      dashboard: 'డాష్‌బోర్డ్',
      overview: 'అవలోకనం',
      statistics: 'గణాంకాలు',
      activity: 'కార్యకలాపం',
      recentActivity: 'ఇటీవలి కార్యకలాపం',
      notifications: 'నోటిఫికేషన్‌లు',
      settings: 'సెట్టింగ్‌లు',
      help: 'సహాయం',
      support: 'మద్దతు',
      logout: 'లాగ్‌అవుట్',
      profile: 'ప్రొఫైల్',
      account: 'ఖాతా',
      preferences: 'ప్రాధాన్యతలు',
      security: 'భద్రత',
      privacy: 'గోప్యత',
      data: 'డేటా',
      export: 'ఎగుమతి',
      import: 'దిగుమతి',
      backup: 'బ్యాకప్',
      restore: 'పునరుద్ధరణ',
      delete: 'తొలగించండి',
      archive: 'ఆర్కైవ్',
      unarchive: 'అన్‌ఆర్కైవ్',
      markAsRead: 'చదివినట్లు గుర్తించండి',
      markAllAsRead: 'అన్నింటిని చదివినట్లు గుర్తించండి',
      clearAll: 'అన్నింటిని క్లియర్ చేయండి',
      selectAll: 'అన్నింటిని ఎంచుకోండి',
      deselectAll: 'అన్నింటిని డిసెలెక్ట్ చేయండి',
      bulkActions: 'బల్క్ చర్యలు',
      sortBy: 'ద్వారా క్రమబద్ధీకరించండి',
      filterBy: 'ద్వారా ఫిల్టర్ చేయండి',
      groupBy: 'ద్వారా గ్రూప్ చేయండి',
      viewAs: 'గా వీక్షించండి',
      listView: 'జాబితా వీక్షణ',
      gridView: 'గ్రిడ్ వీక్షణ',
      cardView: 'కార్డ్ వీక్షణ',
      tableView: 'టేబుల్ వీక్షణ',
      compactView: 'కాంపాక్ట్ వీక్షణ',
      detailedView: 'వివరణాత్మక వీక్షణ',
      summaryView: 'సారాంశ వీక్షణ',
      fullView: 'పూర్తి వీక్షణ',
      partialView: 'పాక్షిక వీక్షణ',
      minimalView: 'కనీస వీక్షణ',
      expandedView: 'విస్తరించిన వీక్షణ',
      collapsedView: 'కుదించిన వీక్షణ',
      hiddenView: 'దాచిన వీక్షణ',
      visibleView: 'దృశ్యమాన వీక్షణ',
      publicView: 'ప్రజా వీక్షణ',
      privateView: 'ప్రైవేట్ వీక్షణ',
      sharedView: 'షేర్ చేయబడిన వీక్షణ',
      personalView: 'వ్యక్తిగత వీక్షణ',
      teamView: 'టీమ్ వీక్షణ',
      organizationView: 'సంస్థ వీక్షణ',
      globalView: 'గ్లోబల్ వీక్షణ',
      localView: 'స్థానిక వీక్షణ',
      regionalView: 'ప్రాంతీయ వీక్షణ',
      nationalView: 'జాతీయ వీక్షణ',
      internationalView: 'అంతర్జాతీయ వీక్షణ',
      
      // Additional missing keys
      browseJobListings: 'ఉద్యోగ లిస్టింగ్‌లను బ్రౌజ్ చేయండి',
      trackApplications: 'దరఖాస్తులను ట్రాక్ చేయండి',
      completeProfile: 'మీ ప్రొఫైల్‌ను పూర్తి చేయండి'
    }
  }

  const t = (key) => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}
